/** Base URL for images */
const BASE_URL: string = "https://cddataexchange.blob.core.windows.net/images/trains";

/** Image names for train wagons */
const imageUrls: string[] = [
    "train-carriage-box.png",
    "train-carriage-coal.png",
    "train-carriage-container-blue.png",
    "train-carriage-container-green.png",
    "train-carriage-container-red.png",
    "train-carriage-dirt.png",
    "train-carriage-flatbed-wood.png",
    "train-carriage-flatbed.png",
    "train-carriage-lumber.png",
    "train-carriage-tank-large.png",
    "train-carriage-tank.png",
    "train-carriage-wood.png",
    "train-diesel-a.png",
    "train-diesel-b.png",
    "train-diesel-box-a.png",
    "train-diesel-box-b.png",
    "train-diesel-box-c.png",
    "train-diesel-c.png",
    "train-electric-bullet-a.png",
    "train-electric-bullet-b.png",
    "train-electric-bullet-c.png",
    "train-electric-city-a.png",
    "train-electric-city-b.png",
    "train-electric-city-c.png",
    "train-electric-double-a.png",
    "train-electric-double-b.png",
    "train-electric-double-c.png",
    "train-electric-square-a.png",
    "train-electric-square-b.png",
    "train-electric-square-c.png",
    "train-electric-subway-a.png",
    "train-electric-subway-b.png",
    "train-electric-subway-c.png",
    "train-locomotive-a.png",
    "train-locomotive-b.png",
    "train-locomotive-c.png",
    "train-locomotive-passenger-a.png",
    "train-locomotive-passenger-b.png",
    "train-tram-classic.png",
    "train-tram-modern.png",
    "train-tram-round.png",
];

/**
 * Abbreviations for train wagons
 *
 * Indices in abbreviations correspond to image names in imageUrls above.
 * e.g. index 0 "TCB" corresponds to imageUrls[0] "train-carriage-box.png"
 * e.g. index 1 "TCC" corresponds to imageUrls[1] "train-carriage-coal.png"
 * etc.
 */
const abbreviations: string[] = [
    "TCB",
    "TCC",
    "TCCB",
    "TCCG",
    "TCCR",
    "TCD",
    "TCFW",
    "TCF",
    "TCL",
    "TCTL",
    "TCT",
    "TCW",
    "TDA",
    "TDB",
    "TDBA",
    "TDBB",
    "TDBC",
    "TDC",
    "TEBA",
    "TEBB",
    "TEBC",
    "TECA",
    "TECB",
    "TECC",
    "TEDA",
    "TEDB",
    "TEDC",
    "TESA",
    "TESB",
    "TESC",
    "TESUA",
    "TESUB",
    "TESUC",
    "TLA",
    "TLB",
    "TLC",
    "TLPA",
    "TLPB",
    "TTC",
    "TTM",
    "TTR"
];
